# Spring Boot properties configuration
server.port=8080
server.address=0.0.0.0

# Configure Jackson default formats
spring.jackson.serialization.indent_output=true
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss

# Disable default login screens for debugging ease
spring.main.banner-mode=off

logging.level.org.springframework.web=INFO
logging.level.com.jarlink.debugger=DEBUG
